# Copyright (C) 2024-2025, TESOBE GmbH
# Email: contact@tesobe.com
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Namespace }}-apiexplorer-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/issuer: letsencrypt-real
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: {{ .Values.defaultDomain }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Namespace }}-apiexplorer-service
              port:
                number: 81
  tls:
    - hosts:
        - {{ .Values.defaultDomain}}
      secretName: apiexplorer-tls-cert