# Copyright (C) 2024-2025, TESOBE GmbH
# Email: contact@tesobe.com
apiVersion: v1
kind: Service
metadata:
    name: "{{ .Release.Namespace }}-apimanager-nginx-service"
    namespace: {{.Release.Namespace}}
spec:
    selector:
        app: "{{ .Release.Namespace }}-apimanager-nginx"
    ports:
    - name: http
      protocol: TCP
      port: 84
      targetPort: 8080
    type: ClusterIP
