# Copyright (C) 2024-2025, TESOBE GmbH
# Email: contact@tesobe.com
apiVersion: v1
kind: Service
metadata:
    name: "{{ .Release.Namespace }}-apimanager-service"
    namespace: {{ .Release.Namespace }}
spec:
    selector:
        app: "{{ .Release.Namespace }}-apimanager"
    ports:
    - name: http
      protocol: TCP
      port: 83
      targetPort: 8000
    type: ClusterIP
