# Copyright (C) 2024-2025, TESOBE GmbH
# Email: contact@tesobe.com
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Namespace}}-apimanager-credentials
type: Opaque
data:
  OAUTH_CONSUMER_KEY: {{ .Values.apimanager_consumer_key }}
  OAUTH_CONSUMER_SECRET: {{ .Values.apimanager_consumer_secret }}
  SECRET_KEY: {{ .Values.apimanager_secret_key }}