# Copyright (C) 2024-2025, TESOBE GmbH
# Email: contact@tesobe.com
apiVersion: v1
kind: Secret
metadata:
    name: keystores-secret
    namespace: rabbit
type: Opaque
data:
    truststore.jks: {{ .Values.truststore }}
    keystore.jks: {{ .Values.keystore }}