# Copyright (C) 2024-2025, TESOBE GmbH
# Email: contact@tesobe.com
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Namespace }}-deployment
  labels:
    app: {{ .Release.Namespace }}-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Namespace }}-api
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: {{ .Release.Namespace }}-api
    spec:
      containers:
        - name: {{ .Release.Namespace }}-api
          image: {{ .Values.image }}
          resources: {}
          #  requests:
          #    memory: "512Mi"
          envFrom:
            - secretRef:
                name: {{.Release.Namespace}}-api-credentials
          env:
{{- range $key, $value := .Values.api }}
            - name: OBP_{{ $key | upper | replace "." "_" }}
              value: {{ $value | quote }}
{{- end }}
            - name: OBP_KEYSTORE_PATH
              value: /mnt/keystores/keystore.jks
            - name: OBP_TRUSTSTORE_PATH
              value: /mnt/keystores/truststore.jks
            - name: JAVA_OPTIONS
              value: {{ .Values.config. }}
          volumeMounts:
            - name: keystores
              mountPath: /mnt/keystores
              readOnly: true
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /obp/v4.0.0/root
              port: 8080
            initialDelaySeconds: 180
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /obp/v4.0.0/root
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 50
      volumes:
          - name: keystores
            secret:
              secretName: keystores-secret