# Copyright (C) 2024-2025, TESOBE GmbH
# Email: contact@tesobe.com
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Namespace }}-apiexplorer-ii-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  VITE_OBP_CONSUMER_KEY: {{ .Values.apiexplorer_ii_consumer_key }}
  VITE_OBP_CONSUMER_SECRET: {{ .Values.apiexplorer_ii_consumer_secret }}
  VITE_OPB_SERVER_SESSION_PASSWORD: {{ .Values.apiexplorer_ii_server_session_password }}
