apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Namespace }}-apiexplorer-ii-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  OBP_OAUTH_CLIENT_SECRET: {{ .Values.obp_oauth_client_secret }}
  KEYCLOAK_OAUTH_CLIENT_SECRET: {{ .Values.keycloak_oauth_client_secret }}
  REDIS_PW: {{ .Values.redis_password }}
  SESSION_SECRET: {{ .Values.session_secret }}